import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>
            <div><Link href='/folders'>Listado de carpetas</Link></div>
            <div><Link href='/dashboards'>Listado de dashboards</Link></div>
            <div><Link href='/panels'>Listado de paneles</Link></div>
        </nav>
        {children}
      </body>
    </html>
  );
}
